# -*- coding: utf-8 -*-
"""speech recognition demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHLL_IQqGoq8MwOjkoArMZEGQimmZvcN
"""

!pip install SpeechRecognition

!apt install libasound2-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg
!pip install PyAudio

import pyaudio
pa = pyaudio.PyAudio()
pa.get_default_input_device_info()

import speech_recognition as sr
r = sr.Recognizer()

with sr.Microphone() as source:
    print('start listening')
    audio= r.listen(source)
    print('listening end')

try:
    print('text:', r.recognize_google(audio));
except:
    pass;